# Site settings
baseurl = "https://example.com/"
title = "Hugo Story Theme"
paginate = 5
buildFuture = true

[[menu.social]]
  name = "GitHub"
  title = "fab fa-github-square"
  url = "https://github.com/xaprb/story/"

[[menu.main]]
  name = "Talks"
  title = "Talks"
  url = "/talks/"

[[menu.main]]
  name = "Slides"
  title = "Slides"
  url = "/slides/"

[[menu.main]]
  name = "Archives"
  title = "Archives"
  url = "/archives/"

[params]
  author = "Jane Smith"
  twitter = "sometwitteruser"
  classes = []

[outputs]
  home = ["HTML", "JSON", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML", "RSS"]
